Extra2/Extra2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('nflrapp/', include('nflrapp.urls'))
]

Extra2/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

Extra2/nflrapp/urls.py
from django.urls import path
from nflrapp import views

app_name = 'nflrapp'

urlpatterns = [
    path('ciudad/list/', views.ListCiudades.as_view(), name='list_ciudades'),  #'asi se vera el path del buscador, views.name of the view.as_view', name= nombre del path(ese se usa en el base)
    path('ciudad/create/', views.CreateCiudad.as_view(), name='create_ciudades'),
    path('ciudad/detail/<int:pk>/', views.DetailCiudad.as_view(), name='detail_ciudades'),
    path('ciudad/update/<int:pk>/', views.UpdateCiudad.as_view(), name='update_ciudades'),
    path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='delete_ciudades'),
    
    path('duenios/list/', views.ListDuenios.as_view(), name='list_duenios'),
    path('duenios/create/', views.CreateDuenios.as_view(), name='create_duenios'),
    path('duenios/detail/<int:pk>/', views.DetailDuenios.as_view(), name='detail_duenios'),
    path('duenios/update/<int:pk>/', views.UpdateDuenios.as_view(), name='update_duenios'),
    path('duenios/<int:pk>/delete/', views.DeleteDuenios.as_view(), name='delete_duenios'),
    
    path('equipos/list/', views.ListEquipos.as_view(), name='list_equipos'),
    path('equipos/create/', views.CreateEquipos.as_view(), name='create_equipos'),
    path('equipos/detail/<int:pk>/', views.DetailEquipos.as_view(), name='detail_equipos'),
    path('equipos/update/<int:pk>/', views.UpdateEquipos.as_view(), name='update_equipos'),
    path('equipos/<int:pk>/delete/', views.DeleteEquipos.as_view(), name='delete_equipos'),
    
    path('jugadores/list/', views.ListJugadores.as_view(), name='list_jugadores'),
    path('jugadores/create/', views.CreateJugadores.as_view(), name='create_jugadores'),
    path('jugadores/detail/<int:pk>/', views.DetailJugadores.as_view(), name='detail_jugadores'),
    path('jugadores/update/<int:pk>/', views.UpdateJugadores.as_view(), name='update_jugadores'),
    path('jugadores/<int:pk>/delete/', views.DeleteJugadores.as_view(), name='delete_jugadores'),
    
    path('estadios/list/', views.ListEstadios.as_view(), name='list_estadios'),
    path('estadios/create/', views.CreateEstadios.as_view(), name='create_estadios'),
    path('estadios/detail/<int:pk>/', views.DetailEstadios.as_view(), name='detail_estadios'),
    path('estadios/update/<int:pk>/', views.UpdateEstadios.as_view(), name='update_estadios'),
    path('estadios/<int:pk>/delete/', views.DeleteEstadios.as_view(), name='delete_estadios'),
]

Extra2/nflrapp/models.py
from django.db import models

# Create your models here.

class Ciudad(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    
    def __str__(self):
        return self.nombre
    
class Duenio(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    
    def __str__(self):
        return self.nombre
    
class Equipo(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    venue = models.CharField(max_length=30)
    duenio = models.ForeignKey(Duenio, on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre
    
class Jugador(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    numero = models.CharField(max_length=3)
    posicion = models.CharField(max_length=30)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre
    
class Estadio(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    capacidad = models.CharField(max_length=30)
    size = models.CharField(max_length=30)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

Extra2/nflrapp/forms.py
from django import forms
from .models import Ciudad, Duenio, Equipo, Jugador, Estadio

class CiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ["nombre"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre de la ciudad "}),
        }
        
class DuenioForm(forms.ModelForm):
    class Meta:
        model = Duenio
        fields = ["nombre"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del Dueño "}),
        }
        
class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = ["nombre", "venue", "duenio", "ciudad"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del Equipo "}),
            "venue": forms.TextInput(attrs={"class": "form-control", "placeholder": "Venue "}),
            "duenio": forms.Select(attrs={"class": "form-control"}),
            "ciudad": forms.Select(attrs={"class": "form-control"}), 
        }
        
class JugadorForm(forms.ModelForm):
    class Meta:
        model = Jugador
        fields = ["nombre", "numero", "posicion", "equipo"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del Jugador "}),
            "numero": forms.TextInput(attrs={"class": "form-control", "placeholder": "Numero del Jugador "}),
            "posicion": forms.TextInput(attrs={"class": "form-control", "placeholder": "Posicion del Jugador "}),
            "equipo": forms.Select(attrs={"class": "form-control"}), 
        }
        
class EstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ["nombre", "capacidad", "size", "equipo", "ciudad"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del Estadio "}),
            "capacidad": forms.TextInput(attrs={"class": "form-control", "placeholder": "Capacidad del estadio "}),
            "size": forms.TextInput(attrs={"class": "form-control", "placeholder": "Box Size "}),
            "equipo": forms.Select(attrs={"class": "form-control"}), 
            "ciudad": forms.Select(attrs={"class": "form-control"}), 
        }

Extra2/nflrapp/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .models import Ciudad, Duenio, Equipo, Jugador, Estadio
from .forms import CiudadForm, DuenioForm, EquipoForm, JugadorForm, EstadioForm
from django.views import generic

# Create your views here.

def home(request):
    return render(request, "home.html")

#Views para Ciudad
class ListCiudades(generic.View):
    template_name = "ciudades/list_ciudades.html"  #"name of the folder/filename.html"
    context = {}

    def get(self, request):
        self.context = {
            "ciudades": Ciudad.objects.all()
        }
        return render(request, self.template_name, self.context)
    
class CreateCiudad(CreateView):
    template_name = "ciudades/create_ciudades.html"
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy('nflrapp:list_ciudades')  #('nombre de la app:nombre del template)
    
class DetailCiudad(DetailView):
    template_name = "ciudades/detail_ciudades.html"
    model = Ciudad
    context_object_name = 'ciudad'

class UpdateCiudad(UpdateView):
    template_name = "ciudades/update_ciudades.html"
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy('nflrapp:list_ciudades')  #('nombre de la app:nombre del template)
    
class DeleteCiudad(DeleteView):
    template_name = "ciudades/delete_ciudades.html"
    model = Ciudad
    success_url = reverse_lazy('nflrapp:list_ciudades')
    

#Views para Dueño  
class ListDuenios(generic.View):
    template_name = "duenios/list_duenios.html"  #"name of the folder/filename.html"
    context = {}

    def get(self, request):
        self.context = {
            "duenios": Duenio.objects.all()
        }
        return render(request, self.template_name, self.context)
    
class CreateDuenios(CreateView):
    template_name = "duenios/create_duenios.html"
    model = Duenio
    form_class = DuenioForm
    success_url = reverse_lazy('nflrapp:list_duenios')  #('nombre de la app:nombre del template)
    
class DetailDuenios(DetailView):
    template_name = "duenios/detail_duenios.html"
    model = Duenio
    context_object_name = 'duenio'

class UpdateDuenios(UpdateView):
    template_name = "duenios/update_duenios.html"
    model = Duenio
    form_class = DuenioForm
    success_url = reverse_lazy('nflrapp:list_duenios')  #('nombre de la app:nombre del template)
    
class DeleteDuenios(DeleteView):
    template_name = "duenios/delete_duenios.html"
    model = Duenio
    success_url = reverse_lazy('nflrapp:list_duenios')  
    
#Views para el Equipo  
class ListEquipos(generic.View):
    template_name = "equipos/list_equipos.html"  #"name of the folder/filename.html"
    context = {}

    def get(self, request):
        self.context = {
            "equipos": Equipo.objects.all()
        }
        return render(request, self.template_name, self.context)
    
class CreateEquipos(CreateView):
    template_name = "equipos/create_equipos.html"
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('nflrapp:list_equipos')  #('nombre de la app:nombre del template)
    
class DetailEquipos(DetailView):
    template_name = "equipos/detail_equipos.html"
    model = Equipo
    context_object_name = 'equipo'

class UpdateEquipos(UpdateView):
    template_name = "equipos/update_equipos.html"
    model = Equipo
    form_class =   EquipoForm
    success_url = reverse_lazy('nflrapp:list_equipos')  #('nombre de la app:nombre del template)
    
class DeleteEquipos(DeleteView):
    template_name = "equipos/delete_equipos.html"
    model = Equipo
    success_url = reverse_lazy('nflrapp:list_equipos')  
    
#Views para el Jugador  
class ListJugadores(generic.View):
    template_name = "jugadores/list_jugadores.html"  #"name of the folder/filename.html"
    context = {}

    def get(self, request):
        self.context = {
            "jugadores": Jugador.objects.all()
        }
        return render(request, self.template_name, self.context)
    
class CreateJugadores(CreateView):
    template_name = "jugadores/create_jugadores.html"
    model = Jugador
    form_class = JugadorForm
    success_url = reverse_lazy('nflrapp:list_jugadores')  #('nombre de la app:nombre del template)
    
class DetailJugadores(DetailView):
    template_name = "jugadores/detail_jugadores.html"
    model = Jugador
    context_object_name = 'jugador'

class UpdateJugadores(UpdateView):
    template_name = "jugadores/update_jugadores.html"
    model = Jugador
    form_class = JugadorForm
    success_url = reverse_lazy('nflrapp:list_jugadores')  #('nombre de la app:nombre del template)
    
class DeleteJugadores(DeleteView):
    template_name = "jugadores/delete_jugadores.html"
    model = Jugador
    success_url = reverse_lazy('nflrapp:list_jugadores') 
    
#Views para el Estadio  
class ListEstadios(generic.View):
    template_name = "estadios/list_estadios.html"  #"name of the folder/filename.html"
    context = {}

    def get(self, request):
        self.context = {
            "estadios": Estadio.objects.all()
        }
        return render(request, self.template_name, self.context)
    
class CreateEstadios(CreateView):
    template_name = "estadios/create_estadios.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy('nflrapp:list_estadios')  #('nombre de la app:nombre del template)
    
class DetailEstadios(DetailView):
    template_name = "estadios/detail_estadios.html"
    model = Estadio
    context_object_name = 'estadio'

class UpdateEstadios(UpdateView):
    template_name = "estadios/update_estadios.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy('nflrapp:list_estadios')  #('nombre de la app:nombre del template)
    
class DeleteEstadios(DeleteView):
    template_name = "estadios/delete_estadios.html"
    model = Estadio
    success_url = reverse_lazy('nflrapp:list_estadios') 

Extra2/nflrapp/templates/jugadores/create_jugadores.html
{% extends "base/base.html" %}

{% block title %}Añadir Jugador{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h1>Añade un Jugador</h1>
            <form action="{% url 'nflrapp:create_jugadores' %}" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Añadir</button>
                <a href="{% url 'nflrapp:list_equipos' %}" class="btn btn-secondary">Cancelar</a>
         </form>
        </div>
    </div>
</div>
{% endblock content %}

Extra2/nflrapp/templates/jugadores/delete_jugadores.html
{% extends "base/base.html" %}

{% block title %}
 Eliminar Jugador
{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h1>¿estas seguro que quieres eliminar al jugador:</h1>
            <h1>{{jugador.nombre}} ?</h1>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Eliminar</button>
                <a href="{% url 'nflrapp:list_jugadores' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Extra2/nflrapp/templates/jugadores/detail_jugadores.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del Jugador
{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h1>Jugador </h1>
            <table class="table table-hover">
                <thead>
                    <th>Numero</th>
                    <th>Nombre</th>
                    <th>Numero del Jugador</th>
                    <th>Posicion</th>
                    <th>Equipo</th>
                </thead>
                <tbody>
                    <tr>
                        <td>{{jugador.codigo}}</td>
                        <td>{{jugador.nombre}}</td>
                        <td>{{jugador.numero}}</td>
                        <td>{{jugador.posicion}}</td>
                        <td>{{jugador.equipo.nombre}}</td>
                    </tr>
                </tbody>
            </table>
            <a href="{% url 'nflrapp:list_jugadores' %}" class="btn btn-secondary">Volver a la lista de Jugadores</a>
        </div>
    </div>
</div>
{% endblock content %}

Extra2/nflrapp/templates/jugadores/list_jugadores.html
{% extends "base/base.html" %}

{% block title %}Jugadores{% endblock title %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h1>Lista de Jugadores</h1>
            <table class="table table-hover">
                <thead>
                    <th>Numero</th>
                    <th>Nombre</th>
                    <th>Numero del Jugador</th>
                    <th>Posicion</th>
                    <th>Equipo</th>
                    <th>Opciones</th>
                </thead>
                <tbody>
                    <a href="{% url 'nflrapp:create_jugadores' %}" class="btn btn-success">Añadir Jugador</a>
                    {% for jugador in jugadores %}
                        <tr>
                            <td>{{jugador.codigo}}</td>
                            <td>{{jugador.nombre}}</td>
                            <td>{{jugador.numero}}</td>
                            <td>{{jugador.posicion}}</td>
                            <td>{{jugador.equipo.nombre}}</td>
                            <td>
                                <a href="{% url 'nflrapp:detail_jugadores' jugador.codigo %}" class="btn btn-info">Detalles</a>
                                <a href="{% url 'nflrapp:update_jugadores' jugador.codigo %}" class="btn btn-warning">Editar</a>
                                <a href="{% url 'nflrapp:delete_jugadores' jugador.codigo %}" class="btn btn-danger">Eliminar</a>
                              </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

Extra2/nflrapp/templates/jugadores/update_jugadores.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Jugador
{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h1>Actualiza los datos del Jugador</h1>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a href="{% url 'nflrapp:list_jugadores' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}